# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIx3A3eZag7Od8xXTQkoPj-S1LE-5IxC
"""

# Class for Customer details
class Customer:
    def __init__(self, customerID, name, email, phoneNumber, nationality):
        self._customerID = customerID  # Private attribute
        self._name = name  # Private attribute
        self._email = email
        self._phoneNumber = phoneNumber
        self._nationality = nationality

    # Getter and Setter for customerID
    def get_customerID(self):
        return self._customerID

    def set_customerID(self, customerID):
        self._customerID = customerID

    # Getter and Setter for name
    def get_name(self):
        return self._name

    def set_name(self, name):
        self._name = name

    # Getter and Setter for email
    def get_email(self):
        return self._email

    def set_email(self, email):
        self._email = email

    # Getter and Setter for phoneNumber
    def get_phoneNumber(self):
        return self._phoneNumber

    def set_phoneNumber(self, phoneNumber):
        self._phoneNumber = phoneNumber

    # Getter and Setter for nationality
    def get_nationality(self):
        return self._nationality

    def set_nationality(self, nationality):
        self._nationality = nationality

    def register_customer(self):
        pass

    def send_confirmation_email(self):
        pass

# Class for Reservation details
class Reservation:
    def __init__(self, bookingID, guestName, totalNights, totalRooms, totalCost):
        self._bookingID = bookingID
        self._guestName = guestName
        self._totalNights = totalNights
        self._totalRooms = totalRooms
        self._totalCost = totalCost

    # Getter and Setter for bookingID
    def get_bookingID(self):
        return self._bookingID

    def set_bookingID(self, bookingID):
        self._bookingID = bookingID

    # Getter and Setter for guestName
    def get_guestName(self):
        return self._guestName

    def set_guestName(self, guestName):
        self._guestName = guestName

    # Getter and Setter for totalNights
    def get_totalNights(self):
        return self._totalNights

    def set_totalNights(self, totalNights):
        self._totalNights = totalNights

    # Getter and Setter for totalRooms
    def get_totalRooms(self):
        return self._totalRooms

    def set_totalRooms(self, totalRooms):
        self._totalRooms = totalRooms

    # Getter and Setter for totalCost
    def get_totalCost(self):
        return self._totalCost

    def set_totalCost(self, totalCost):
        self._totalCost = totalCost

    def book_room(self):
      pass

    def upgarde_room(self):
      pass

# Class for Hotel details
class Hotel:
    def __init__(self, hotelName, phone, address, checkInTime, checkOutTime):
        self._hotelName = hotelName
        self._phone = phone
        self._address = address
        self._checkInTime = checkInTime
        self._checkOutTime = checkOutTime

    # Getter and Setter for hotelName
    def get_hotelName(self):
        return self._hotelName

    def set_hotelName(self, hotelName):
        self._hotelName = hotelName

    # Getter and Setter for phone
    def get_phone(self):
        return self._phone

    def set_phone(self, phone):
        self._phone = phone

    # Getter and Setter for address
    def get_address(self):
        return self._address

    def set_address(self, address):
        self._address = address

    # Getter and Setter for checkInTime
    def get_checkInTime(self):
        return self._checkInTime

    def set_checkInTime(self, checkInTime):
        self._checkInTime = checkInTime

    # Getter and Setter for checkOutTime
    def get_checkOutTime(self):
        return self._checkOutTime

    def set_checkOutTime(self, checkOutTime):
        self._checkOutTime = checkOutTime


# Class for Payment details
class Payment:
    def __init__(self, billingName, creditCardType, creditCardNumber, subtotal, totalAmount):
        self._billingName = billingName
        self._creditCardType = creditCardType
        self._creditCardNumber = creditCardNumber
        self._subtotal = subtotal
        self._totalAmount = totalAmount

    # Getter and Setter for billingName
    def get_billingName(self):
        return self._billingName

    def set_billingName(self, billingName):
        self._billingName = billingName

    # Getter and Setter for creditCardType
    def get_creditCardType(self):
        return self._creditCardType

    def set_creditCardType(self, creditCardType):
        self._creditCardType = creditCardType

    # Getter and Setter for creditCardNumber
    def get_creditCardNumber(self):
        return self._creditCardNumber

    def set_creditCardNumber(self, creditCardNumber):
        self._creditCardNumber = creditCardNumber

    # Getter and Setter for subtotal
    def get_subtotal(self):
        return self._subtotal

    def set_subtotal(self, subtotal):
        self._subtotal = subtotal

    # Getter and Setter for totalAmount
    def get_totalAmount(self):
        return self._totalAmount

    def set_totalAmount(self, totalAmount):
        self._totalAmount = totalAmount

    def process_payment(self):
      pass

    def generate_invoice(self):
      pass

# Class for Room details
class Room:
    def __init__(self, roomNumber, roomType, pricePerNight):
        self._roomNumber = roomNumber
        self._roomType = roomType
        self._pricePerNight = pricePerNight
        self._roomAmenities = "Basic"

    # Getter and Setter for roomNumber
    def get_roomNumber(self):
        return self._roomNumber

    def set_roomNumber(self, roomNumber):
        self._roomNumber = roomNumber

    # Getter and Setter for roomType
    def get_roomType(self):
        return self._roomType

    def set_roomType(self, roomType):
        self._roomType = roomType

    # Getter and Setter for pricePerNight
    def get_pricePerNight(self):
        return self._pricePerNight

    def set_pricePerNight(self, pricePerNight):
        self._pricePerNight = pricePerNight

    # Getter and Setter for roomAmenities (extra attribute)
    def get_roomAmenities(self):
        return self._roomAmenities

    def set_roomAmenities(self, roomAmenities):
        self._roomAmenities = roomAmenities

    def send_booking_confirmation(self):
      pass

# Class for Cancellation details
class Cancellation:
    def __init__(self, cancellationID, cancellationDate, refundAmount, bookingID, customerDetails):
        self._cancellationID = cancellationID
        self._cancellationDate = cancellationDate
        self._refundAmount = refundAmount
        self._bookingID = bookingID
        self._customerDetails = customerDetails

    # Getter and Setter for cancellationID
    def get_cancellationID(self):
        return self._cancellationID

    def set_cancellationID(self, cancellationID):
        self._cancellationID = cancellationID

    # Getter and Setter for cancellationDate
    def get_cancellationDate(self):
        return self._cancellationDate

    def set_cancellationDate(self, cancellationDate):
        self._cancellationDate = cancellationDate

    # Getter and Setter for refundAmount
    def get_refundAmount(self):
        return self._refundAmount

    def set_refundAmount(self, refundAmount):
        self._refundAmount = refundAmount

    # Getter and Setter for bookingID
    def get_bookingID(self):
        return self._bookingID

    def set_bookingID(self, bookingID):
        self._bookingID = bookingID

    # Getter and Setter for customerDetails
    def get_customerDetails(self):
        return self._customerDetails

    def set_customerDetails(self, customerDetails):
        self._customerDetails = customerDetails

# Class for LoyaltyProgram details
class LoyaltyProgram:
    def __init__(self, programID, programName, rewardPoints, customerID, discountRate):
        self._programID = programID
        self._programName = programName
        self._rewardPoints = rewardPoints
        self._customerID = customerID
        self._discountRate = discountRate

    # Getter and Setter for programID
    def get_programID(self):
        return self._programID

    def set_programID(self, programID):
        self._programID = programID

    # Getter and Setter for programName
    def get_programName(self):
        return self._programName

    def set_programName(self, programName):
        self._programName = programName

    # Getter and Setter for rewardPoints
    def get_rewardPoints(self):
        return self._rewardPoints

    def set_rewardPoints(self, rewardPoints):
        self._rewardPoints = rewardPoints

    # Getter and Setter for customerID
    def get_customerID(self):
        return self._customerID

    def set_customerID(self, customerID):
        self._customerID = customerID

    # Getter and Setter for discountRate
    def get_discountRate(self):
        return self._discountRate

    def set_discountRate(self, discountRate):
        self._discountRate = discountRate


# Example output
customer = Customer("C123", "Ted Vera", "tedvera@mac.com", "505-661-1110", "USA")
reservation = Reservation("1554B805358", "Ted Vera", 2, 1, 201.48)
hotel = Hotel("Comfort Inn & Suites Los Alamos", "505-661-1110", "2455 Trinity Drive, Los Alamos, NM 87544", "Sun, Aug 22, 2010 - 03:00 PM", "Tue, Aug 24, 2010 - 12:00 PM")
payment = Payment("Ted H Vera", "Mastercard", 9904, 179.90, 201.48)
loyalty_program = LoyaltyProgram("LP001", "Abu Dhabi Rewards", 500, "C123", 10.0)
cancellation = Cancellation("CAN123", "Oct 13, 2024", 1300.0, "ABDX12345", "Fatima Saeed")

# Print output
print("Your Reservation is Confirmed\n")
print("Name: " + customer.get_name())
print("Email: " + customer.get_email())
print("Hotel: " + hotel.get_hotelName())
print("Check-In: " + hotel.get_checkInTime())
print("Check-Out: " + hotel.get_checkOutTime())
print("Room Type: " + str(reservation.get_totalRooms()) + " room(s), " + str(reservation.get_totalNights()) + " night(s)\n")
print("Summary of Charges: ")
print("Billing Name: " + payment.get_billingName())
print("Booking ID: " + reservation.get_bookingID())
print("Room Charges: $" + str(reservation.get_totalCost()))
print("Credit Card Type: " + payment.get_creditCardType())
print("Credit Card Number: " + str(payment.get_creditCardNumber()))
print("Subtotal: $" + str(payment.get_subtotal()))
print("Total Amount: $" + str(payment.get_totalAmount()))

print()
# Print Loyalty Program details
print("Loyalty Program Details:")
print("Program ID: " + loyalty_program.get_programID())
print("Program Name: " + loyalty_program.get_programName())
print("Reward Points: " + str(loyalty_program.get_rewardPoints()))
print("Discount Rate: " + str(loyalty_program.get_discountRate()) + "%")

print()
# Print Cancellation details
print("Cancellation Details:")
print("Cancellation ID: " + cancellation.get_cancellationID())
print("Cancellation Date: " + cancellation.get_cancellationDate())
print("Refund Amount: $" + str(cancellation.get_refundAmount()))
print("Booking ID: " + cancellation.get_bookingID())
print("Customer: " + cancellation.get_customerDetails())

